### ISSUE TITLE
Open Ticket

### ISSUE THREAD

**Issue by bonxz** [ElBedus/discord-TicketBot#1]
What is the command for open ticket?

used this %tb #tickets

```
[-] Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.description: This field is required

```

**Comment by ElBedus** [comment]
This command sends a message to "#channel" with a button for creating tickets.
The description of this button is taken from the last message in the chat.
![Screenshot_1](https://user-images.githubusercontent.com/87133177/164974005-671f3de5-c577-4a42-96f6-c9ef366ab980.png)

Example:
![Screenshot_2](https://user-images.githubusercontent.com/87133177/164974013-3ead04ef-a17a-4788-8b67-ca532658882e.png)

Now a message with a button for creating tickets and a description "To create a ticket, click the button below" has appeared in the "#general" channel

**Comment by bonxz** [comment]
ok got it.

but why does the bot need a role with administrator privileges?
I have assigned the bot a role in which it has all rights except the "administrator" one. 

i get this error then.
```
Unhandled exception in internal background task 'button_detect'.
Traceback (most recent call last):
  File "C:\Users\Tommy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\Tommy\Desktop\ticketbot\cogs\tickets.py", line 120, in button_detect
    await channel.send(embed=embed)
  File "C:\Users\Tommy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord_components\dpy_overrides.py", line 350, in send_override
    return await send(channel, *args, **kwargs)
  File "C:\Users\Tommy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord_components\dpy_overrides.py", line 325, in send
    data = await state.http.send_message(
  File "C:\Users\Tommy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

```

If I give the bot the role with admin privileges, it works. maybe it can be adjusted?

**Comment by ElBedus** [comment]
The bot does not necessarily need an administrator perms. He needs perms to create channels, send messages and a few more.

If such an error occurs, then the bot does not have the rights to send messages to this channel. Perhaps the channel settings do not allow him to do this.
(I'll update the bot later and make a normal description)

**Comment by bonxz** [comment]
Okay, yes, I've got most of it figured out now. I'm not a Python pro :D

Would it still be possible to customise the embed with pictures and author and so on?
Like this
![image](https://user-images.githubusercontent.com/61289944/164980100-20c683f5-e341-42db-a947-7045add9dbbb.png)



This is the code but I can't get it integrated.
```
embed=discord.Embed(title="Möchten Sie ein Ticket erstellen?", description="Wenn Sie eine Frage oder ein Anliegen haben, erstellen Sie bitte ein Ticket, indem Sie auf das 📩-Emoji klicken.", color=0x4ee444)
embed.set_author(name="zeroManager Tickets", icon_url="https://cdn.discordapp.com/avatars/778614418623037451/9209c4ef98f5270e68d316f7d6f00cc2.png?size=4096")
embed.set_thumbnail(url="https://cdn.discordapp.com/avatars/778614418623037451/9209c4ef98f5270e68d316f7d6f00cc2.png?size=4096")
embed.add_field(name="Allgemeine Fragen!", value="Wenn Sie allgemeine Fragen zum Ticketsystem haben, wenden Sie sich bitte an einen Supporter!", inline=False)
embed.set_footer(text="Ticket Bot")
await ctx.send(embed=embed)
```

**Comment by bonxz** [comment]
And I have discovered another error or optimisation. That was also the error with the admin rights earlier.

If the bot has less rights than I do and I open the ticket as an admin. Then I can't use the "Close ticket" button. Because the bot can't take away my rights.

**Comment by ElBedus** [comment]
Embed customization will be done a little later.

As for the fact that the admin can write to a closed ticket - this is normal. In any case, no one can forbid the admin to write messages.

**Comment by bonxz** [comment]
> As for the fact that the admin can write to a closed ticket - this is normal. In any case, no one can forbid the admin to write messages.

You have misunderstood me. I mean when someone opens a ticket with a role higher than the bot itself. Then the ticket opener can't "close" the ticket because the bot can't change the permissions because its role is too low. Then maybe an error message should be inserted by the bot.

**Comment by bonxz** [comment]
![image](https://user-images.githubusercontent.com/61289944/165131771-2626953f-ae1e-41ef-8049-7f9e13c398b3.png)

And it would be cool if you could add something like this with ticket logs

**Comment by ElBedus** [comment]
The bot does not change the rights of individual users. Instead, it changes the permissions for the @everyone role. Thus, it does not matter what role the one who opened the ticket has. If he does not have administrator rights, he will not be able to write in this channel.

I hope I got it right this time :D
